services:
  #  postgres:
  #    container_name: postgres-db
  #    image: postgres
  #    environment:
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: secret
  #      PGDATA: /var/lib/postgresql/data
  #      POSTGRES_DB: book_social_network
  #    volumes:
  #      - postgres:/data/postgres
  #    ports:
  #      - 5432:5432
  #    networks:
  #      - spring-demo
  #    restart: unless-stopped
  #  mysql:
  #    image: mysql:latest
  #    container_name: mysql-db
  #    ports:
  #      - "3306:3306"
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=secret
  #      - MYSQL_DATABASE=chatreservas
  #    restart: unless-stopped
  #    volumes:
  #      - /home/usuario/db/mysql:/var/lib/mysql
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
